<a href="https://colab.research.google.com/github/zamanfarah00/NumericalMethods/blob/main/condition_Number.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n = int(input("Enter Matrix size :"))
A = np.zeros((n,n)) #initialize kora hoise ,
#matrix ke initally zero rakha hoise
for i in range(n):
  for j in range(n):
    A[i][j] = float(input(f"A[{i}][{j}]="))

Enter Matrix size :3
A[0][0]=1
A[0][1]=1
A[0][2]=1
A[1][0]=0
A[1][1]=2
A[1][2]=2
A[2][0]=1
A[2][1]=1
A[2][2]=2


In [ ]:
print(A)

[[1. 1. 1.]
 [0. 2. 2.]
 [1. 1. 2.]]


**DIRECT LIBRARY**

In [ ]:
if np.linalg.det(A)!=0:
  print("1-norm= ",np.linalg.cond(A,1))
  print("2-norm= ",np.linalg.cond(A,2))
  print("Infinity- norm= ",np.linalg.cond(A,np.inf))
else:
  print("Matrix is singular")


1-norm=  15.0
2-norm=  8.45909178002303
Infinity- norm=  10.0


**MANUAL WAY**

In [ ]:
A_inv = np.linalg.inv(A)

col_sum1 = []
col_sum2 = []

for j in range(n):
  sum1 = 0
  sum2 = 0
  for i in range(n):
    sum1 = sum1 + abs(A[i][j])
    sum2 = sum2 + abs(A_inv[i][j])
  col_sum1.append(sum1)
  col_sum2.append(sum2)

condA = max(col_sum1) * max(col_sum2)
condA


np.float64(15.0)

In [ ]:
A_inv = np.linalg.inv(A)

row_sum3 = []
row_sum4 = []

for i in range(n):
  sum3 = 0
  sum4 = 0
  for j in range(n):
    sum3 = sum3 + abs(A[i][j])
    sum4 = sum4 + abs(A_inv[i][j])
  row_sum3.append(sum3)
  row_sum4.append(sum4)

condA = max(row_sum3) * max(row_sum4)
condA


np.float64(10.0)